# Generated by Django 4.2 on 2023-05-10 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLolitas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('price', models.FloatField()),
                ('stock', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True,
                 null=True, upload_to='productos/')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
            },
        ),
    ]
