# Generated by Django 4.2 on 2023-05-17 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLolitas', '0003_servicios_alter_producto_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
